sudo: required
services:
  - docker

before_install:
  - docker build -t rehovoti/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true rehovoti/react-test npm test
after_success:
  - docker build -t rehovoti/multi-client ./client
  - docker build -t rehovoti/multi-nginx ./nginx
  - docker build -t rehovoti/multi-server ./server
  - docker build -t rehovoti/multi-worker ./worker
# push all the images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push docdoc123/rehovoti:rehovoti/multi-client
  - docker push docdoc123/rehovoti:rehovoti/multi-nginx
  - docker push docdoc123/rehovoti:rehovoti/multi-server
  - docker push docdoc123/rehovoti:rehovoti/multi-worker
